language: minimal

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "asutosh"
  - git config --local user.email "abc@email.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

env:
  global:
    secure: up9qxEwVAEvRT2YxYVJ49fbYyVeUwKR14YYBL6tf7iCgIsnXLwcyPeC5UCtsJUfih0CSFIu/vTRQvaHeNZ8JH9GoXMILWZpu2qSoEP7EgyJBh58HWWSkbHAheqNi06OwJdfJLEMyPfz1gFKIWdidt8hdtMfjkuvg6J4uQSq/fUXYrjjahev68DpHARitWNOSdiwmL2nZ515EMh0WV/oCbw5rWDwnWSXT5d6erRccu2LJBjKK6x6ymKpuMCgPwMp2veQyc0OtiMPGNYAWHwEeWeDAI4Sa6ohJTKZg5G1qYSamIZ01WUAxlgJV2YxHD4sd1Bp69Yo90ZW5aKigF9WHdOjBIYJO6vS8zKGBNrro8kr/iwA8BcGX8ryjE4hgdb4HTvIELI9paj+Y5FMJ5vojztryEhAoYGxTge3hFXuq/+kXp4iVPqo3LjF95nSlWkJ0CpyO7Wr72gyjFB7pasQxvthT5OndEE5aJylju2HKIVdQ2MPD7oeLJWWGVcbKY5a58SqpwQL2+15Ok+xnfVQKTrcxc8wuFDkPOlc39BGmI8qWeH+WFC3Es9PxLnghmbmTqw0bHlKhVxbfD2fuS4TJJvemw2IJyvOZnnndgsW7dS4kL/h2UUaZXGEF6oWbc+r9L8QAs6PaMYcOyJA6nik0KtDguki1afr64AXTz4ZEEaE=
deploy:
  provider: releases
  api_key: avwUe4DY3irFzMqkwYoKk9Awqc8a3PpaRBB2L7Ilhjf8sWv9URiruJ60lKrJpfmNLcCNYT8g188esTb4Vo42haEwjPmoW5qI6vvT64UWatxsrS4te4MD+Sr4lvlmNH6z9cRhrg+XClwRaRhXK8Gy744NZcahdYhgVthr4jIQoZE6Z6iGEXw8iGgX60Wlpi3B6tuIdiNu24bo6FOjwTThmr2xuaIkcXdVeklLyR/rM22KpBIOvowrAsA3aevBhV9BhfCDIEtWcda4ZMpIBaRxumi+Rd7i0ao+Y4FSVQt9P6/l7+5X+9JuFxVqaoEkWGhFSlmJKRPTSN8xirVLq/gQKYTr2FgOfOCJV2/o5h7w9LQEXS6x2VjOcM6rTy/gr4I2hSbt8bV4062ppOUfN/Z9pYFFiF/gSO5vv2GIJY2Kil+11DVH3WtFxtnfkuMGG0uPEiqZC6/AGU1BGvXz6d7Wcc3bXVuXgIub1crl6Vx8NrXztWUHpU86HhmWszayYd/6rnc/zTmlQhgATWR9O2FPBN2j+b1ioo3WvErWM9LHy7bIa0lgUiHo48HBo0SssoHxseK4PT14TtTppJMFe7gfDMixDzmNnY6e9MwDwuXk1hUz/+Vtv7q6y1j2Y3S8jMeq4R4UP4AAAimh+mAI9CQ3qK67uhsg5Z/mJhklzZ2+iq4=
  file: README.md
  cleanup: true
  on:
    tags: false
    branch: main
