language: minimal

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "asutosh"
  - git config --local user.email "abc@email.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "179570b561c14bcf0f19f97fa442b6ec5966fd9b"
  file: README.md
  cleanup: true
  on:
    tags: false
    branch: main
